---
ip: "192.168.50.140"
memory: 1024
cpus: 2

networking:
    - public: true

folders:
    - map: .
      to: /var/www/redis-worker
      type: nfs

php: 7

nginx: true

#ports:
#  - guest: 80
#    host: 8898